# Generated by Django 3.1.2 on 2021-02-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nid_no', models.CharField(max_length=200)),
                ('date_created', models.CharField(max_length=200)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdraw_amount', models.IntegerField()),
                ('serviceuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingSystem.serviceuser')),
            ],
        ),
        migrations.CreateModel(
            name='SendMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('serviceuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingSystem.serviceuser')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.IntegerField()),
                ('serviceuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingSystem.serviceuser')),
            ],
        ),
    ]
